apiVersion: v1
kind: ConfigMap
metadata:
  name: decidim-sen-app-config
  labels:
    app: decidim-sen-app
data:
  RAILS_ENV: production
  RAILS_SERVE_STATIC_FILES: "true"
  APP_NAME: "decidim_sen"
  WEB_CONCURRENCY: "0"
  CACHE_ASSETS: "true"
