apiVersion: apps/v1
kind: Deployment
metadata:
  name: decidim-sen-deployment
spec:
  selector:
    matchLabels:
      app: decidim-sen-app
  template:
    metadata:
      labels:
        app: decidim-sen-app
    spec:
      containers:
      - name: decidim-sen-app
        image: rg.fr-par.scw.cloud/decidim-sen/decidim-sen:latest
        resources:
          requests:
            cpu: "900m"
            memory: "1250Mi"
          limits:
            cpu: "1024m"
            memory: "1500Mi"
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
              name: decidim-sen-app-config
          - secretRef:
              name: decidim-sen-app-secrets
